/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package profile;

import org.junit.Test;

public class AppTest
{
    @Test
    public void appHasAGreeting()
    {
	Profile classUnderTest = new Profile();
    }
}
